document.writeln("<textarea cols ='100' rows='10'>");
document.writeln("Contoh Memambahkan Enter");
document.writeln("Muhammad \nAgus \nLuthfi");
document.writeln("Contoh Memambahkan Tab");
document.writeln("Muhammad \tAgus \tLuthfi");
document.writeln("Contoh Memambahkan Putip 1");
document.writeln("Muhammad \'Agus \'Luthfi");
document.writeln("Contoh Memambahkan Putip 2");
document.writeln("Muhammad \"Agus \"Luthfi");
document.writeln("Contoh Memambahkan Garis Miring");
document.writeln("Muhammad \\Agus \\Luthfi");
document.writeln("</textarea>");
